version: '3'
services:
  postgresql:
    image: postgres:13.4-alpine
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_PASSWORD=kruger1234
      - POSTGRES_USER=kruger
      - POSTGRES_DB=kruger-inventory